language: node_js
node_js: "node" # Latest stable Node.js release
cache:
  directories:
    - node_modules # Our node modules
    - $HOME/.npm # Globally installed packages, e.g. NPM

install:
  - npm install
  - npm update # Ensure to use latest versions of dependencies

stages:
  - name: lint
    if: type = pull_request OR branch = master
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      script: skip
      deploy:
        provider: npm
        email: tech@maas.global
        api_key: $NPM_TOKEN
      after_deploy: ./scripts/tag.sh
